apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: herd-model-cache-pvc
  labels:
    app: herd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # Adjust size based on the number and size of models you want to host
